module.exports = {
  variants: [
    'typography.html',
    'images.html',
    'tables.html',
    'forms.html',
    'navs.html',
    'accordion.html',
    'alerts.html',
    'badges.html',
    'buttons.html',
    'breadcrumb.html',
    'card.html',
    'code.html',
    'dropdowns.html',
    'listgroups.html',
    'pagination.html',
    'popovers.html',
    'progress.html',
    'modal.html',
    'scrollspy.html',
    'spinners.html',
    'toasts.html',
    'tooltips.html',
    'carousel.html',
    'shadows.html',
    'utils.html'
  ]
}
